
mqtt:
  server: tcp://zhangtory.com:1883
  clientid: WebServer-test
  username: username
  password: password

server:
  port: 8086

spring:
  quartz:
    job-store-type: jdbc
    properties:
      org:
        quartz:
          scheduler:
            instanceName: clusteredScheduler
            instanceId: AUTO
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_
            useProperties: false
            dataSource: myDs
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
          dataSource:
            myDs:
              driver: com.mysql.cj.jdbc.Driver
              URL: jdbc:mysql://databaseUrl:3306/yourDatabaseName
              user: username
              password: password

